### ISSUE TITLE
Copying a quiz links it to the original

### ISSUE THREAD

**Issue by profgrumpy** [cereal-lab/EvoPIE#108]
If we copy a quiz, changing the "deadline driven" flag on the original also changes it on the copy. It is possible there are other things, like the deadlines configuration that are also shared by the two.

**Comment by profgrumpy** [comment]
Addendum; if we make a copy of a copy of a quiz using the button in the UI, this one is not updated when we check its "deadline driven" box

**Comment by dvitel** [comment]
The issue was that one quiz was assigned to several courses. The view "Quiz Browser" shows actually a list of quiz deployments. Ideally, we would like to have QuizDeployment entity (currently Course_Quizes table) where we need to move a bunch of columns from Quiz entity (all grading settings, see models.py). Currently applied fix: quiz could have a relation to only one course. To have same quiz in different courses, it have to be copied. Fix changed the way we select available quizzes to a new course. Now, quizzes are filtered out if they already have a relation to any other course.

**Comment by dvitel** [comment]
In case if we decide to go with the QuizDeployment entity, we can reopen this issue. The roadmap would include developing new view - one for quiz another for quiz deployment and UI for copying grading settings for same quiz from different course. 

1. Schema changes: move columns from Quiz to Course_Quiz and rename Course_Quiz to QuizDeployment. (course_id, quiz_id) is a key of deployment and any table which reference quiz with quiz_id should be reinvestigated.
2. Fix all CRUD operations with modified entities 
3. Copy quiz browser to quiz deployment browser 
4. Develop a modal to migrade grading schema

Currently, this is not planned.
