### ISSUE TITLE
Unable to take step 2 of a quiz that has been transitioned by hand

### ISSUE THREAD

**Issue by profgrumpy** [cereal-lab/EvoPIE#123]
The transition step 1 to step 2 via deadline seems to work fine. However, when I have a quiz set manually to step 1, take it as a student, then manually set it to step 2, it prevents me to take step 2 as a student, claiming that step 1 is not available.

**Comment by dvitel** [comment]
I tried to reproduce it. It seems that such situation happens only when student did not take step 1 but quiz is already on step 2. Clicking "Take quiz" in this case indeed gives message "Step 1 of this quiz is not available" - since for a student the first step is Step 1. I am thinking that it would make sense to hide "Take quiz" button in all situations which would lead to error message. If we know that quiz is already on Step 2, and student did not take Step 1 - simply do not show the button.

**Comment by dvitel** [comment]
I hide Take Quiz button if status of the quiz != quiz_attempt.status
