### ISSUE TITLE
Likes Progress bar issues during step2

### ISSUE THREAD

**Issue by profgrumpy** [cereal-lab/EvoPIE#47]
If a student opens twice in a row a quiz during step2, without submitting the first time, then the likes progress bar shows 0 likes given even though the student already gave some and they even show on the page.

Also, the bar should be red to start off with since 0 likes is not going to grant participation points to the student.

**Comment by neverdue** [comment]
I fixed the issue for the first part!

For the second part, "Also, the bar should be red to start off with since 0 likes is not going to grant participation points to the student."

I was thinking that the blue acts as a neutral color and when they start liking they see that they are in the red zone and when they enter the range of participation it becomes green and when they go out again it becomes red. I thought that the blue was meshing in the red and green. However, this is just my opinion, if you do feel like the bar should start off red for 0 likes I can do that but then when they give a like, what would the bar be like then?

**Comment by neverdue** [comment]
Sorry for the long comment, here's the commit for the first part (f3f42d5)

**Comment by profgrumpy** [comment]
I guess the bar color can be somewhat of a subjective matter :)
Where I came from: at 0 likes, the student does not get any participation, hence the warning. Same as if they exceed the max likes allowed.
I'd say no need to change the color for the first like except if that put them in the green range.

**Comment by profgrumpy** [comment]
suggestion: when you display the number of likes in the bar, I would add "give a few more" or "give a few less" as a message after the number. or something like "5 likes given (8 min, 17 max)"

**Comment by neverdue** [comment]
Pushed a commit for this (cabb753)

**Comment by neverdue** [comment]
Issue with the bar - not sticking to the bottom at all times!

**Comment by neverdue** [comment]
Pushed a commit for this (be22bbf)
